# ==========================================
# 1. PERMANENT CONFIGURATION (Input Data)
# ==========================================

# MARKETING_LIMIT: A Float. Stores the maximum allowed budget for Marketing.
MARKETING_LIMIT = float(input("Set the Permanent Marketing Limit: "))

# SOFTWARE_LIMIT: A Float. Stores the maximum allowed budget for Software.
SOFTWARE_LIMIT = float(input("Set the Permanent Software Limit: "))


# ==========================================
# 2. STORAGE & TRACKERS (Global Variables)
# ==========================================

# expenses_history: A List of Dictionaries. This is our "Database" to store all entries.
expenses_history = []

# success_count: An Integer. Keeps track of how many entries were "SAFE" (under limit).
success_count = 0

# total_revenue: A Float. An accumulator variable to sum up all incoming money.
total_revenue = 0.0

# total_expenses: A Float. An accumulator variable to sum up all spending.
total_expenses = 0.0


print("\n--- Smart Audit & Profit Engine ---")


# ==========================================
# 3. DATA COLLECTION LOOP (Logic & Variables)
# ==========================================

# This loop runs as long as the list length is less than 10.
while len(expenses_history) < 10:
    
    # count: An Integer. Represents the current entry number (e.g., Entry 1/10).
    count = len(expenses_history) + 1
    print(f"\nEntry {count}/10")
    
    # --- Inner Validation Loop ---
    while True:
        # cat: A String. Stores the department name after cleaning (strip/capitalize).
        cat = input("Category (Marketing/Software): ").strip().capitalize()
        if cat in ["Marketing", "Software"]:
            break
        print("❌ Invalid Category! Please type 'Marketing' or 'Software'.")
    
    # amt: A Float. The specific cost for this one transaction.
    amt = float(input(f"Enter expense amount for {cat}: "))
    
    # rev: A Float. The money generated from this specific transaction.
    rev = float(input(f"Enter revenue generated by this {cat} action: "))
    
    # profit: A Float. A calculated variable (Revenue - Expense).
    profit = rev - amt
    
    # Updating our global accumulators
    total_revenue += rev
    total_expenses += amt
    
    # limit: A Float. A conditional variable that switches based on the 'cat' selected.
    limit = MARKETING_LIMIT if cat == "Marketing" else SOFTWARE_LIMIT
    
    # status: A String. Labels the data as 'SAFE' or 'DANGER' based on the business rule.
    status = "SAFE" if amt <= limit else "DANGER"
    
    if status == "SAFE": 
        success_count += 1
    
    # Adding a new "Row" (Dictionary) to our list
    expenses_history.append({
        "ID": count, 
        "Cat": cat, 
        "Amt": amt, 
        "Rev": rev, 
        "Prof": profit, 
        "Stat": status
    })


# ==========================================
# 4. FINAL ANALYTICS (Result Variables)
# ==========================================

# success_rate: A Float. Percentage of entries that stayed within budget.
success_rate = (success_count / 10) * 100

# total_profit_loss: A Float. The final bottom line of the business session.
total_profit_loss = total_revenue - total_expenses

# avg_profit: A Float. The mathematical mean profit across the 10 entries.
avg_profit = total_profit_loss / 10


# ==========================================
# 5. REPORT GENERATION (Formatting Variables)
# ==========================================

# output_lines: A List of Strings. We collect all report rows here before saving.
output_lines = [
    "="*75,
    "📊 FINAL BUSINESS PERFORMANCE REPORT",
    "-" * 75,
    f"{'ID':<4} | {'CAT':<12} | {'EXPENSE':<10} | {'REVENUE':<10} | {'PROFIT':<10} | {'STATUS'}",
    "-" * 75
]

# row: A Dictionary. A temporary variable used in the loop to pull data from the list.
for row in expenses_history:
    # line: A String. A formatted row of text for the table.
    line = f"{row['ID']:<4} | {row['Cat']:<12} | ${row['Amt']:<9.2f} | ${row['Rev']:<9.2f} | ${row['Prof']:<9.2f} | {row['Stat']}"
    output_lines.append(line)

# final_report: A String. The giant block of text created by joining all lines.
final_report = "\n".join(output_lines)


# ==========================================
# 6. PERSISTENCE (File Output)
# ==========================================

print(final_report)

# Saving the data so it isn't lost when the program closes.
with open("audit_report.txt", "w") as file:
    file.write(final_report)

print("\n📁 Success! Your report has been saved to 'audit_report.txt'")
