# 1. PERMANENT CONFIGURATION
MARKETING_LIMIT = float(input("Set the Permanent Marketing Limit: "))
SOFTWARE_LIMIT = float(input("Set the Permanent Software Limit: "))

# 2. STORAGE & TRACKERS
expenses_history = []
success_count = 0
total_revenue = 0.0
total_expenses = 0.0

print("\n--- Smart Audit & Profit Engine ---")

# 3. DATA COLLECTION LOOP (10 entries)
while len(expenses_history) < 10:
    count = len(expenses_history) + 1
    print(f"\nEntry {count}/10")
    
    # Validation Loop: Force user to pick correct category
    while True:
        cat = input("Category (Marketing/Software): ").strip().capitalize()
        if cat in ["Marketing", "Software"]:
            break
        print("❌ Invalid Category! Please type 'Marketing' or 'Software'.")
    
    amt = float(input(f"Enter expense amount for {cat}: "))
    rev = float(input(f"Enter revenue generated by this {cat} action: "))
    
    # Profit calculation
    profit = rev - amt
    total_revenue += rev
    total_expenses += amt
    
    # Comparison logic
    limit = MARKETING_LIMIT if cat == "Marketing" else SOFTWARE_LIMIT
    status = "SAFE" if amt <= limit else "DANGER"
    
    if status == "SAFE": success_count += 1
    
    # Append to database
    expenses_history.append({
        "ID": count, "Cat": cat, "Amt": amt, "Rev": rev, "Prof": profit, "Stat": status
    })

# 4. CALCULATIONS
success_rate = (success_count / 10) * 100
total_profit_loss = total_revenue - total_expenses
avg_profit = total_profit_loss / 10

# 5. GENERATE TABULAR REPORT
report_header = f"{'ID':<4} | {'CAT':<12} | {'EXPENSE':<10} | {'REVENUE':<10} | {'PROFIT':<10} | {'STATUS'}"
divider = "-" * 75

output_lines = [
    "="*75,
    "📊 FINAL BUSINESS PERFORMANCE REPORT",
    divider,
    report_header,
    divider
]

for row in expenses_history:
    line = f"{row['ID']:<4} | {row['Cat']:<12} | ${row['Amt']:<9.2f} | ${row['Rev']:<9.2f} | ${row['Prof']:<9.2f} | {row['Stat']}"
    output_lines.append(line)

output_lines.append(divider)
output_lines.append(f"✅ SUCCESS RATE: {success_rate}%")
output_lines.append(f"💰 TOTAL NET PROFIT/LOSS: ${total_profit_loss:.2f}")
output_lines.append(f"📈 AVG PROFIT PER ENTRY: ${avg_profit:.2f}")
output_lines.append("="*75)

# 6. PRINT TO TERMINAL AND SAVE TO FILE (Persistence)
final_report = "\n".join(output_lines)
print(final_report)

with open("audit_report.txt", "w") as file:
    file.write(final_report)

print("\n📁 Success! Your report has been saved to 'audit_report.txt'")
